### ISSUE TITLE
Publish to Homebrew

### ISSUE THREAD

**Issue by antonbabenko** [keygen-sh/keygen-cli#1]
It is much more convenient for users to manage tools there.

PS: I learned about this CLI from the newsletter.

**Comment by ezekg** [comment]
Good idea, but I think we're going to focus on distributing with our own service for the time being. Typically, Homebrew likes a project to be a couple years old before being added to the tap (I know, I have a tap or two on Homebrew already). As this CLI matures, perhaps we can revisit, but for now we're going to stick to using Keygen itself to distribute the CLI.
