### ISSUE TITLE
Permissions error with automatic installation

### ISSUE THREAD

**Issue by mgd722** [keygen-sh/keygen-cli#9]
Run the auto install as [suggested in the docs](https://keygen.sh/docs/cli/):
```
curl -sSL https://get.keygen.sh/keygen/latest/install.sh | sh
```
Returns this on my M1 MacBook Pro:
```
[info] successfully downloaded v2.2.0 for darwin/arm64: /tmp/keygen.GXM5QkpWJx/keygen
mv: rename /tmp/keygen.GXM5QkpWJx/keygen to /usr/local/bin/keygen: Permission denied
[error] failed to installed v2.2.0 for darwin/arm64 (please install manually via https://keygen.sh/docs/cli/)
```
No worries, I can run a manual installation but still have to `sudo mv` to get things in place. Once that's all done, the first time I try to run the command I get a scary notice from Apple saying they can't scan this for viruses and won't run the script. Not my first rodeo, so I go into Privacy & Security settings and explicitly allow it and Apple finally lets it run.

Is my system being wonky, or is this expected behavior? I wish I had screenshot the Apple warning message, because it was slightly different than the normal one and it mentioned to contact the developer.

**Comment by ezekg** [comment]
You shouldn't need to run `sudo` to move something to `/usr/local/bin`. Sounds like your permissions are wonky.

**Comment by mgd722** [comment]
I just created another user account on my machine and got the same thing (granted, sharing a drive).

Once I get home I'll try it on my wife's Mac and see if I still get the same error-- I'm sure she wouldn't have messed with her permissions the same way I may have done in the past.

**Comment by mgd722** [comment]
Everything worked as expected on my coworker's Mac (13.31), but on mine and my wife's (13.4) we get blocked. Still can't say for sure it's related to the MacOS version though.

I'll close this for now since it's trivial to work around.
